-- SELECT * FROM EMP;
-- SELECT * FROM DEPT;
-- SELECT * FROM PROJ;
-- SELECT * FROM EMPPROJ;

-- basic

-- SELECT E.FIRST_NAME AS "name", D.DEPT_NAME AS "department"
-- FROM EMP E JOIN DEPT D ON E.DEPT_ID = D.DEPT_ID
-- WHERE D.DEPT_NAME = 'IT';

-- SELECT FIRST_NAME, SALARY FROM EMP
-- WHERE SALARY > 75000;

-- SELECT LAST_NAME FROM EMP
-- ORDER BY LAST_NAME ASC;

-- SELECT E.FIRST_NAME AS "name",E.SALARY, D.DEPT_NAME AS "department"
-- FROM EMP E JOIN DEPT D ON E.DEPT_ID = D.DEPT_ID
-- WHERE D.DEPT_NAME = 'Sales'
-- ORDER BY E.SALARY DESC;

-- manipulation

-- UPDATE EMP
-- SET SALARY = SALARY + 10000
-- WHERE EMP_ID = 101;

-- UPDATE EMP 
-- SET SALARY = SALARY *  1.05
-- FROM DEPT 
-- WHERE EMP.DEPT_ID = DEPT.DEPT_ID
-- AND DEPT.DEPT_NAME = 'IT';

-- DELETE FROM EMPPROJ
-- WHERE EMP_ID = 105;
-- DELETE FROM EMP
-- WHERE EMP_ID = 105;

-- joins

-- SELECT CONCAT(E.FIRST_NAME,' ',E.LAST_NAME) AS "name", P.PROJ_NAME AS "project", D.DEPT_NAME AS "department"
-- FROM EMP E 
-- INNER JOIN DEPT D ON D.DEPT_ID = E.DEPT_ID
-- INNER JOIN EMPPROJ EP ON E.EMP_ID = EP.EMP_ID 
-- INNER JOIN PROJ P ON P.PROJ_ID = EP.PROJ_ID
-- WHERE P.PROJ_NAME = 'API Development'

-- SELECT D.DEPT_NAME AS "department", COUNT(E.EMP_ID) AS "number_of_employees"
-- FROM DEPT D
-- LEFT JOIN EMP E ON D.DEPT_ID = E.DEPT_ID
-- GROUP BY D.DEPT_NAME;

-- aggregation

-- SELECT AVG(SALARY,2) AS "average_salary",SUM(SALARY) AS "total_salary" FROM EMP;

-- SELECT ROUND(COALESCE(AVG(E.SALARY),0),2) AS "average_salary", D.DEPT_NAME AS "department"
-- FROM DEPT D
-- LEFT JOIN EMP E ON E.DEPT_ID = D.DEPT_ID
-- GROUP BY D.DEPT_NAME
-- HAVING COALESCE(AVG(E.SALARY),0) > 80000;