CREATE TABLE IF NOT EXISTS DEPT (
    DEPT_ID INT PRIMARY KEY,
    DEPT_NAME VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS EMP (
    EMP_ID SERIAL PRIMARY KEY,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    POSITION VARCHAR(100),
    SALARY DECIMAL(10, 2),
    HIRE_DATE DATE,
    DEPT_ID INT,
-- one-to-one relationship with DEP
    FOREIGN KEY (DEPT_ID) REFERENCES DEPT(DEPT_ID)
);

CREATE TABLE IF NOT EXISTS PROJ (
    PROJ_ID INT PRIMARY KEY,
    PROJ_NAME VARCHAR(100) NOT NULL
);

-- Junction table for many-to-many relationship between EMP and PROJ
CREATE TABLE IF NOT EXISTS EMPPROJ (
    EMP_ID INT,
    PROJ_ID INT,
    PRIMARY KEY (EMP_ID, PROJ_ID),
    FOREIGN KEY (EMP_ID) REFERENCES EMP(EMP_ID),
    FOREIGN KEY (PROJ_ID) REFERENCES PROJ(PROJ_ID)
);
